### ISSUE TITLE
Forge loading crash in 1.8.9 modpack

### ISSUE THREAD

**Issue by Hydrargiros** [VikeStep/sprinkles_for_vanilla#44] opened 2016-03-15 00:27 UTC
Hi, im a modpack creator, i want to use you mod in one of my modpacks, but it seems to crash with it. I leave the log here so you can check it.

[fml-client-latest.txt](https://github.com/VikeStep/sprinkles_for_vanilla/files/173072/fml-client-latest.txt)

**Comment by squeek502** [comment] 2016-03-15 01:01
Looks like the same incompatibility with AppleCore that exists in 1.7.10. See https://github.com/squeek502/AppleCore/issues/45#issuecomment-175356999

Not sure when it'll get fixed. For now, you'll have to remove either sprinkles_for_vanilla or AppleCore.

**Comment by VikeStep** [comment] 2016-03-16 06:47
So, is this a problem in my mod, ASMHelper or AppleCore @squeek502

**Comment by CrystalMageX** [comment] 2016-03-16 16:12
This seems to be a problem with _cross-mod compatibility_ between sprinkles_for_vanilla and AppleCore. (I am not familiar with ASMHelper, and I don't know if it can do anything to help).

The problem is that both of your mods are transforming the `BlockSapling` and `BlockCrops` classes, and either Java or ASM does not seem to like that. ([sprinkles_for_vanilla](https://github.com/VikeStep/sprinkles_for_vanilla/blob/e8a1f342e1867ffe3d5bba08aada2852ff51b553/src/main/java/io/github/vikestep/sprinklesforvanilla/asm/SprinklesForVanillaTransformer.java#L793), [AppleCore](https://github.com/squeek502/AppleCore/blob/35f3962e9d5f95785c39813fe9637db191029ce9/java/squeek/applecore/asm/module/ModulePlantGrowth.java#L203)) Passing the command line flag `-noverify` to the launcher though, allows Minecraft to start normally on 1.7.10. I've tested bone-mealing crops in creative, during day, and during night, and the game **did not crash**. (I haven't tested neither the functionality of both mods, nor the blocks' ability to grow in survival mode. Using this workaround is a **bad idea** because `-noverify` _requires additional work_ to set up, _looks scary_ to normal players, and might help _circumvent any forge security_.

A good solution would be to **detect AppleCore** and:
- Use its [`squeek.applecore.api.plants.PlantGrowthEvent`](https://github.com/squeek502/AppleCore/blob/1.7.10/java/squeek/applecore/api/plants/PlantGrowthEvent.java) if it is installed.
- Run the current transformer when it is not present.

**Comment by mcgraj3** [comment] 2016-05-24 23:49
Just wanted to stop in here and confirm this. I have run Sprinkles for Vanilla for a long time now, and adding AppleCore caused a crash. I'd really like to see a fix as I am not fond of random forest fires, Enderman griefing and mob crop trampling. :)

**Comment by squeek502** [comment] 2016-05-25 05:47
@mcgraj3 @VikeStep This will be fixed in the next version of AppleCore.

**Comment by VikeStep** [comment] 2016-05-25 05:48
Thanks @squeek502, I will close this issue. If it occurs again @mcgraj3 please reopen it. Thank you.

**Closed as completed by VikeStep** 2016-05-25 05:48 UTC
